# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        # 设置主窗口对象名称
        MainWindow.setObjectName("MainWindow")
        # 设置主窗口大小
        MainWindow.resize(873, 691)
        # 创建中央部件
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 创建一个框架部件
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 40, 810, 531))
        self.frame.setMinimumSize(QtCore.QSize(810, 531))
        # 设置框架部件的样式
        self.frame.setStyleSheet("#frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        # 设置框架部件的形状和阴影
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # 创建一个垂直布局
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        # 创建一个框架部件
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        # 设置框架部件的样式
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:20px;\n"
"border-top-right-radius:20px;")
        # 设置框架部件的形状和阴影
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        # 创建一个水平布局
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # 创建一个框架部件
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        # 设置框架部件的形状和阴影
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        # 创建一个水平布局
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # 创建一个按钮部件
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        # 设置按钮部件的样式
        self.pushButton.setStyleSheet("border:none;\n"
"font: 87 9pt \"Arial Black\";\n"
"color: rgb(0, 255, 255);\n"
"color: rgb(144, 211, 255);")
        # 创建一个图标
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/水资源.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # 设置按钮部件的图标
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        # 将按钮部件添加到水平布局中
        self.horizontalLayout_2.addWidget(self.pushButton, 0, QtCore.Qt.AlignLeft)
        # 将水平布局添加到框架部件中
        self.horizontalLayout.addWidget(self.frame_4)
        # 创建一个框架部件
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        # 设置框架部件的样式
        self.frame_5.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        # 设置框架部件的形状和阴影
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        # 创建一个水平布局
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        # 创建一个按钮部件
        self.pushButton_Logout = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Logout.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Logout.setText("")
        # 创建一个图标
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # 设置按钮部件的图标
        self.pushButton_Logout.setIcon(icon1)
        self.pushButton_Logout.setObjectName("pushButton_Logout")
        # 将按钮部件添加到水平布局中
        self.horizontalLayout_3.addWidget(self.pushButton_Logout)
        # 创建一个按钮部件
        self.pushButton_Minimize = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Minimize.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Minimize.setText("")
        # 创建一个图标
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # 设置按钮部件的图标
        self.pushButton_Minimize.setIcon(icon2)
        self.pushButton_Minimize.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_Minimize.setObjectName("pushButton_Minimize")
        # 将按钮部件添加到水平布局中
        self.horizontalLayout_3.addWidget(self.pushButton_Minimize)
        # 创建一个按钮部件
        self.pushButton_Close = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_Close.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_Close.setText("")
        # 创建一个图标
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # 设置按钮部件的图标
        self.pushButton_Close.setIcon(icon3)
        self.pushButton_Close.setObjectName("pushButton_Close")
        # 将按钮部件添加到水平布局中
        self.horizontalLayout_3.addWidget(self.pushButton_Close)
        # 将水平布局添加到框架部件中
        self.horizontalLayout.addWidget(self.frame_5, 0, QtCore.Qt.AlignRight)
        # 将框架部件添加到垂直布局中
        self.verticalLayout.addWidget(self.frame_2)
        # 创建一个框架部件
        self.frame_3 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        # 设置框架部件的样式
        self.frame_3.setStyleSheet("")
        # 设置框架部件的形状和阴影
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        # 创建一个水平布局
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        # 创建一个框架部件
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        # 设置框架部件的样式
        self.frame_6.setStyleSheet("#frame_6{\n"
"    border-bottom-left-radius:20px;\n"
"    border-top-right-radius:20px;\n"
"    background-color: rgb(255, 174, 174);\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(170, 255, 255);\n"
"}\n"
"\n"
"")
        # 设置框架部件的形状和阴影
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        # 创建一个垂直布局
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # 创建一个框架部件
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        # 设置框架部件的样式
        self.frame_10.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(118, 126, 123);\n"
"    font: 11pt \"微软雅黑\";\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_10)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/功能栏.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_2.addWidget(self.frame_10)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(118, 126, 123);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    padding-left:5px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.pushButton_Model_Select = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Model_Select.setGeometry(QtCore.QRect(20, 20, 111, 23))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/模型选择.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Model_Select.setIcon(icon5)
        self.pushButton_Model_Select.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_Model_Select.setObjectName("pushButton_Model_Select")
        self.pushButton_Model_Init = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Model_Init.setGeometry(QtCore.QRect(20, 60, 121, 23))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/初始化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Model_Init.setIcon(icon6)
        self.pushButton_Model_Init.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_Model_Init.setObjectName("pushButton_Model_Init")
        self.line = QtWidgets.QFrame(self.frame_8)
        self.line.setGeometry(QtCore.QRect(0, 0, 163, 1))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_Import_Pic = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Import_Pic.setGeometry(QtCore.QRect(14, 100, 121, 23))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Import_Pic.setIcon(icon7)
        self.pushButton_Import_Pic.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_Import_Pic.setObjectName("pushButton_Import_Pic")
        self.pushButton_Import_Video = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Import_Video.setGeometry(QtCore.QRect(24, 140, 101, 23))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/视频.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Import_Video.setIcon(icon8)
        self.pushButton_Import_Video.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_Import_Video.setObjectName("pushButton_Import_Video")
        self.pushButton_Open_Camera = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Open_Camera.setGeometry(QtCore.QRect(20, 180, 121, 23))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/摄像头.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Open_Camera.setIcon(icon9)
        self.pushButton_Open_Camera.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Open_Camera.setObjectName("pushButton_Open_Camera")
        self.pushButton_Pause = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Pause.setGeometry(QtCore.QRect(0, 220, 121, 23))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/暂停.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Pause.setIcon(icon10)
        self.pushButton_Pause.setIconSize(QtCore.QSize(21, 21))
        self.pushButton_Pause.setObjectName("pushButton_Pause")
        self.pushButton_Over = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_Over.setGeometry(QtCore.QRect(20, 250, 81, 31))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/结束.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Over.setIcon(icon11)
        self.pushButton_Over.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_Over.setObjectName("pushButton_Over")
        self.verticalLayout_2.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(118, 126, 123);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"QPushButton:hover{\n"
"    padding-left:5px;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_Main = QtWidgets.QPushButton(self.frame_9)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/主页.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Main.setIcon(icon12)
        self.pushButton_Main.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_Main.setObjectName("pushButton_Main")
        self.verticalLayout_4.addWidget(self.pushButton_Main)
        self.pushButton_Me = QtWidgets.QPushButton(self.frame_9)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/我的.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Me.setIcon(icon13)
        self.pushButton_Me.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_Me.setObjectName("pushButton_Me")
        self.verticalLayout_4.addWidget(self.pushButton_Me)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("#frame_7{\n"
"    border-bottom-right-radius:20px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_7)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_Main = QtWidgets.QWidget()
        self.page_Main.setObjectName("page_Main")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_Main)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_28 = QtWidgets.QFrame(self.page_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_28.sizePolicy().hasHeightForWidth())
        self.frame_28.setSizePolicy(sizePolicy)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_15.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_28)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(118, 126, 123);\n"
"    font: 10pt \"微软雅黑\";\n"
"}")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/URL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon14)
        self.pushButton_6.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_15.addWidget(self.pushButton_6)
        self.lineEdit_Camera_URL = QtWidgets.QLineEdit(self.frame_28)
        self.lineEdit_Camera_URL.setObjectName("lineEdit_Camera_URL")
        self.horizontalLayout_15.addWidget(self.lineEdit_Camera_URL)
        self.verticalLayout_14.addWidget(self.frame_28)
        self.frame_27 = QtWidgets.QFrame(self.page_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(11)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_30 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_30.sizePolicy().hasHeightForWidth())
        self.frame_30.setSizePolicy(sizePolicy)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.horizontalLayout_16.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(45)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_31.sizePolicy().hasHeightForWidth())
        self.frame_31.setSizePolicy(sizePolicy)
        self.frame_31.setStyleSheet("")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_Camera_Video_Pic = QtWidgets.QLabel(self.frame_31)
        self.label_Camera_Video_Pic.setMinimumSize(QtCore.QSize(489, 351))
        self.label_Camera_Video_Pic.setMaximumSize(QtCore.QSize(489, 351))
        self.label_Camera_Video_Pic.setStyleSheet("background-color: rgb(255, 252, 254);")
        self.label_Camera_Video_Pic.setText("")
        self.label_Camera_Video_Pic.setObjectName("label_Camera_Video_Pic")
        self.verticalLayout_15.addWidget(self.label_Camera_Video_Pic)
        self.horizontalLayout_16.addWidget(self.frame_31)
        self.frame_29 = QtWidgets.QFrame(self.frame_27)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_29.sizePolicy().hasHeightForWidth())
        self.frame_29.setSizePolicy(sizePolicy)
        self.frame_29.setStyleSheet("")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_16.addWidget(self.frame_29)
        self.verticalLayout_14.addWidget(self.frame_27)
        self.frame_26 = QtWidgets.QFrame(self.page_Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame_32 = QtWidgets.QFrame(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_32.sizePolicy().hasHeightForWidth())
        self.frame_32.setSizePolicy(sizePolicy)
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_17.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(60)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setStyleSheet("")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_33)
        self.textBrowser.setStyleSheet("background-color: rgb(255, 252, 254);\n"
"border-bottom-right-radius:20px;\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_18.addWidget(self.textBrowser)
        self.horizontalLayout_17.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.frame_26)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_34.sizePolicy().hasHeightForWidth())
        self.frame_34.setSizePolicy(sizePolicy)
        self.frame_34.setMinimumSize(QtCore.QSize(7, 0))
        self.frame_34.setMaximumSize(QtCore.QSize(7, 16777215))
        self.frame_34.setStyleSheet("")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_17.addWidget(self.frame_34, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_14.addWidget(self.frame_26)
        self.stackedWidget.addWidget(self.page_Main)
        self.page_Me = QtWidgets.QWidget()
        self.page_Me.setObjectName("page_Me")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_Me)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.page_Me)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_13.sizePolicy().hasHeightForWidth())
        self.frame_13.setSizePolicy(sizePolicy)
        self.frame_13.setStyleSheet("#frame_13{\n"
"    background-color: rgb(243, 243, 243);\n"
"    border-top-left-radius:20px;\n"
"    border-bottom-left-radius:20px;\n"
"}\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_17 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(118, 126, 123);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"\n"
"\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_User_Now = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_User_Now.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_User_Now.setMaximumSize(QtCore.QSize(16777215, 25))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/账号.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_User_Now.setIcon(icon15)
        self.pushButton_User_Now.setIconSize(QtCore.QSize(23, 23))
        self.pushButton_User_Now.setObjectName("pushButton_User_Now")
        self.verticalLayout_10.addWidget(self.pushButton_User_Now)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 25))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/大学.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon16)
        self.pushButton_7.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_10.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_8.setMinimumSize(QtCore.QSize(300, 0))
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 25))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/项目.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon17)
        self.pushButton_8.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_10.addWidget(self.pushButton_8)
        self.horizontalLayout_6.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_18.sizePolicy().hasHeightForWidth())
        self.frame_18.setSizePolicy(sizePolicy)
        self.frame_18.setStyleSheet("QPushButton{\n"
"font: 11pt \"微软雅黑\";\n"
"    background-color: rgb(128, 255, 217);\n"
"min-height:25px;    /*设置最小高度*/\n"
"border-radius:10px;    /*设置圆角半径 */\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_Log_Out = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_Log_Out.setObjectName("pushButton_Log_Out")
        self.verticalLayout_9.addWidget(self.pushButton_Log_Out)
        self.pushButton_Change_Password = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_Change_Password.setObjectName("pushButton_Change_Password")
        self.verticalLayout_9.addWidget(self.pushButton_Change_Password)
        self.pushButton_Author = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_Author.setObjectName("pushButton_Author")
        self.verticalLayout_9.addWidget(self.pushButton_Author)
        self.horizontalLayout_6.addWidget(self.frame_18)
        self.horizontalLayout_5.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.frame_14)
        self.label.setMaximumSize(QtCore.QSize(150, 150))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/荷花.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.horizontalLayout_5.addWidget(self.frame_14)
        self.verticalLayout_6.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.page_Me)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setStyleSheet("")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_15)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Proj_Introduction = QtWidgets.QWidget()
        self.page_Proj_Introduction.setObjectName("page_Proj_Introduction")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.page_Proj_Introduction)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_35 = QtWidgets.QFrame(self.page_Proj_Introduction)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.textBrowser_Introduction = QtWidgets.QTextBrowser(self.frame_35)
        self.textBrowser_Introduction.setStyleSheet("")
        self.textBrowser_Introduction.setLineWidth(1)
        self.textBrowser_Introduction.setPlaceholderText("")
        self.textBrowser_Introduction.setObjectName("textBrowser_Introduction")
        self.verticalLayout_16.addWidget(self.textBrowser_Introduction)
        self.horizontalLayout_19.addWidget(self.frame_35)
        self.stackedWidget_2.addWidget(self.page_Proj_Introduction)
        self.page_Change_Password = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_Change_Password.sizePolicy().hasHeightForWidth())
        self.page_Change_Password.setSizePolicy(sizePolicy)
        self.page_Change_Password.setStyleSheet("")
        self.page_Change_Password.setObjectName("page_Change_Password")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_Change_Password)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_20 = QtWidgets.QFrame(self.page_Change_Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_9.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.page_Change_Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setStyleSheet("#frame_21{\n"
"background-color: rgb(255, 244, 252);\n"
"border-radius:20px;\n"
"}")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_24 = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_24.sizePolicy().hasHeightForWidth())
        self.frame_24.setSizePolicy(sizePolicy)
        self.frame_24.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(118, 126, 123);\n"
"    font: 11pt \"微软雅黑\";\n"
"}")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_24)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/密码修改.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon18)
        self.pushButton_9.setIconSize(QtCore.QSize(21, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_10.addWidget(self.pushButton_9)
        self.verticalLayout_11.addWidget(self.frame_24)
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_23.sizePolicy().hasHeightForWidth())
        self.frame_23.setSizePolicy(sizePolicy)
        self.frame_23.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lineEdit_Change_P1 = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_Change_P1.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Change_P1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_Change_P1.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"")
        self.lineEdit_Change_P1.setObjectName("lineEdit_Change_P1")
        self.verticalLayout_12.addWidget(self.lineEdit_Change_P1)
        self.lineEdit_Change_P2 = QtWidgets.QLineEdit(self.frame_23)
        self.lineEdit_Change_P2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_Change_P2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_Change_P2.setStyleSheet("font: 75 11pt \"微软雅黑\";")
        self.lineEdit_Change_P2.setObjectName("lineEdit_Change_P2")
        self.verticalLayout_12.addWidget(self.lineEdit_Change_P2)
        self.verticalLayout_11.addWidget(self.frame_23)
        self.frame_25 = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.frame_25.sizePolicy().hasHeightForWidth())
        self.frame_25.setSizePolicy(sizePolicy)
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_Sure_Change = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_Sure_Change.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_Sure_Change.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_Sure_Change.setStyleSheet("QPushButton{\n"
"font: 11pt \"微软雅黑\";\n"
"background-color: rgb(128, 255, 217);\n"
"min-height:25px;    /*设置最小高度*/\n"
"border-radius:10px;    /*设置圆角半径 */\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.pushButton_Sure_Change.setObjectName("pushButton_Sure_Change")
        self.horizontalLayout_14.addWidget(self.pushButton_Sure_Change)
        self.pushButton_Back = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_Back.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_Back.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton_Back.setStyleSheet("QPushButton{\n"
"font: 11pt \"微软雅黑\";\n"
"background-color: rgb(128, 255, 217);\n"
"min-height:25px;    /*设置最小高度*/\n"
"border-radius:10px;    /*设置圆角半径 */\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.horizontalLayout_14.addWidget(self.pushButton_Back)
        self.verticalLayout_11.addWidget(self.frame_25)
        self.frame_19 = QtWidgets.QFrame(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_19.sizePolicy().hasHeightForWidth())
        self.frame_19.setSizePolicy(sizePolicy)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget_3 = QtWidgets.QStackedWidget(self.frame_19)
        self.stackedWidget_3.setObjectName("stackedWidget_3")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_3.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_3 = QtWidgets.QLabel(self.page_3)
        self.label_3.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 85, 255);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_13.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 85, 255);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setStyleSheet("font: 75 11pt \"微软雅黑\";\n"
"color: rgb(255, 85, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_12.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget_3.addWidget(self.page_2)
        self.horizontalLayout_11.addWidget(self.stackedWidget_3)
        self.verticalLayout_11.addWidget(self.frame_19)
        self.horizontalLayout_9.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.page_Change_Password)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_9.addWidget(self.frame_22)
        self.stackedWidget_2.addWidget(self.page_Change_Password)
        self.verticalLayout_8.addWidget(self.stackedWidget_2)
        self.verticalLayout_7.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(148, 136, 143);\n"
"    font: 11pt \"微软雅黑\";\n"
"}\n"
"")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_16)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon19)
        self.pushButton_4.setIconSize(QtCore.QSize(17, 17))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_8.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_16)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/邮箱.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon20)
        self.pushButton_5.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_8.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_16)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/icons/电话.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon21)
        self.pushButton_3.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.verticalLayout_7.addWidget(self.frame_16)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.page_Me)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(0)
        self.pushButton_Close.clicked.connect(MainWindow.close) # type: ignore
        self.pushButton_Minimize.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " Water Area Detection System"))
        self.pushButton_2.setText(_translate("MainWindow", " 功能区"))
        self.pushButton_Model_Select.setText(_translate("MainWindow", " 选择权重"))
        self.pushButton_Model_Init.setText(_translate("MainWindow", " 模型初始化"))
        self.pushButton_Import_Pic.setText(_translate("MainWindow", " 导入图片"))
        self.pushButton_Import_Video.setText(_translate("MainWindow", " 导入视频"))
        self.pushButton_Open_Camera.setText(_translate("MainWindow", " 开启摄像头"))
        self.pushButton_Pause.setText(_translate("MainWindow", " 暂停"))
        self.pushButton_Over.setText(_translate("MainWindow", " 结束"))
        self.pushButton_Main.setText(_translate("MainWindow", " 主页"))
        self.pushButton_Me.setText(_translate("MainWindow", " 我的"))
        self.pushButton_6.setText(_translate("MainWindow", " Camera URL"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_User_Now.setText(_translate("MainWindow", " 用户：Jarvis"))
        self.pushButton_7.setText(_translate("MainWindow", " 院校：合肥工业大学"))
        self.pushButton_8.setText(_translate("MainWindow", " 项目：基于YOLOv7的水域检测系统"))
        self.pushButton_Log_Out.setText(_translate("MainWindow", "退出登录"))
        self.pushButton_Change_Password.setText(_translate("MainWindow", "修改密码"))
        self.pushButton_Author.setText(_translate("MainWindow", "订阅作者"))
        self.textBrowser_Introduction.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">项目背景：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">    </span><span style=\" font-size:11pt;\">习近平总书记在全国生态环境保护大会上指出要“加快建立现代化生态环境监测体系”，明确了新时期生态环境监测工作的总纲领、总方针、总遵循。当前，国内外环境污染事件频发，尤其是大江大河沿线建设的化工园区，对区域水环境造成重大污染隐患。为此，我们旨在开发一款水域检测系统，通过无人机搭载摄像设备，再使用yolo算法处理实时视频流，识别出污染水域和污染物，并结合磁絮凝技术对污染区域进行去污处理。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">设计思路：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">    首先，无人机应配备摄像设备和水质采样设备。通过摄像设备，我们能够实时采集视频，而水质采样设备不仅可以投放去污药剂，还能采集水样以分析去污效果。而我们的系统主要基于yolov7，并结合OpenCV库对实时视频流进行处理，从而能够识别污染水域和污染物。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">创新点：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">智能化采样与应急处理一体化：</span><span style=\" font-size:11pt;\">将水质采样监控设备与磁絮凝药剂投加设备集成于无人机，实现水质采集、监测与污水应急处理的一体化操作。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">实时监测与应急响应：</span><span style=\" font-size:11pt;\">结合移动终端与水质监控管理，实现人机互动与信息化监测。用户可实时掌握水质状况，发现突发污染时无人机自动投放磁絮凝剂进行应急处理。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">高效磁絮凝技术：</span><span style=\" font-size:11pt;\">优化磁絮凝剂成分比例，污染物去除效率显著提高。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">磁种循环利用：利用粉煤灰和钢厂回收烟尘作为磁种，无需回收，降低成本，促进节能减排。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">无人机系统设计：</span><span style=\" font-size:11pt;\">包括无人机、地面测控中心和手持终端，搭载空中拍摄、飞行控制、水样采集单元，适应不同水质监控任务需求。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">应用前景：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">紧急污染事故的应急处理：</span><span style=\" font-size:11pt;\">无人机在突发水体污染事故中能快速到达现场，进行水质采样、实时监测与自动磁絮凝剂投放，有效降低COD、TP、SS等污染物含量，快速控制污染扩散。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">沿河（湖）化工园区监视：</span><span style=\" font-size:11pt;\">无人机定期巡逻沿河（湖）化工园区，进行水质采样和监测，及时发现潜在污染源，预防污染事件的发生。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">节能减排：</span><span style=\" font-size:11pt;\">利用粉煤灰和钢厂回收烟尘作为磁种，不仅能够变废为宝，还避免了额外的磁种回收的成本，促进资源的循环利用和节能减排。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">应用范围广：</span><span style=\" font-size:11pt;\">项目能够广泛应用于河流、湖泊、工业园区等多种场景，为各级的环保部门、相关水务公司及化工企业提供高效、便捷的水质监测与应急处理方案。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", " 密码修改"))
        self.lineEdit_Change_P1.setPlaceholderText(_translate("MainWindow", "密码："))
        self.lineEdit_Change_P2.setPlaceholderText(_translate("MainWindow", "确认密码："))
        self.pushButton_Sure_Change.setText(_translate("MainWindow", "确认修改"))
        self.pushButton_Back.setText(_translate("MainWindow", "返回"))
        self.label_3.setText(_translate("MainWindow", "两次输入的密码不一致！"))
        self.label_4.setText(_translate("MainWindow", "密码修改成功！"))
        self.label_2.setText(_translate("MainWindow", "输入内容不能为空！"))
        self.pushButton_4.setText(_translate("MainWindow", " 联系我们：邮箱 | 电话"))
        self.pushButton_5.setText(_translate("MainWindow", " 邮箱：1091784993@qq.com"))
        self.pushButton_3.setText(_translate("MainWindow", " 电话：13072266894"))
import res_rc
