# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(851, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoginWindow.sizePolicy().hasHeightForWidth())
        LoginWindow.setSizePolicy(sizePolicy)
        LoginWindow.setMinimumSize(QtCore.QSize(851, 600))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 160, 671, 311))
        self.frame.setStyleSheet("#frame\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 10, 221, 31))
        self.label.setStyleSheet("color: rgb(147, 181, 255);\n"
"font: 87 10pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(400, 10, 141, 31))
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(420, 280, 91, 31))
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"Arial Rounded MT Bold\";")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(620, 10, 31, 31))
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"    border:none;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(22, 22))
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(320, 50, 300, 231))
        self.frame_2.setMinimumSize(QtCore.QSize(300, 231))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_Register = QtWidgets.QWidget()
        self.page_Register.setObjectName("page_Register")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_Register)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_Register_Account = QtWidgets.QLineEdit(self.page_Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Register_Account.sizePolicy().hasHeightForWidth())
        self.lineEdit_Register_Account.setSizePolicy(sizePolicy)
        self.lineEdit_Register_Account.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_Register_Account.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Register_Account.setObjectName("lineEdit_Register_Account")
        self.verticalLayout_6.addWidget(self.lineEdit_Register_Account)
        self.lineEdit_Register_Password = QtWidgets.QLineEdit(self.page_Register)
        self.lineEdit_Register_Password.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_Register_Password.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Register_Password.setText("")
        self.lineEdit_Register_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Register_Password.setObjectName("lineEdit_Register_Password")
        self.verticalLayout_6.addWidget(self.lineEdit_Register_Password)
        self.pushButton_R_Sure_2 = QtWidgets.QPushButton(self.page_Register)
        self.pushButton_R_Sure_2.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_R_Sure_2.setStyleSheet("QPushButton{\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"background-color: rgb(170, 255, 255);\n"
"min-height:25px;    /*设置最小高度*/\n"
"border-radius:10px;    /*设置圆角半径 */\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.pushButton_R_Sure_2.setObjectName("pushButton_R_Sure_2")
        self.verticalLayout_6.addWidget(self.pushButton_R_Sure_2)
        self.stackedWidget_2.addWidget(self.page_Register)
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_Login_Account = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_Login_Account.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_Login_Account.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);\n"
"")
        self.lineEdit_Login_Account.setObjectName("lineEdit_Login_Account")
        self.verticalLayout_5.addWidget(self.lineEdit_Login_Account)
        self.lineEdit_Login_Password = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_Login_Password.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit_Login_Password.setStyleSheet("font: 87 10pt \"Arial Black\";\n"
"color: rgb(0, 0, 0);")
        self.lineEdit_Login_Password.setText("")
        self.lineEdit_Login_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Login_Password.setObjectName("lineEdit_Login_Password")
        self.verticalLayout_5.addWidget(self.lineEdit_Login_Password)
        self.pushButton_L_Sure = QtWidgets.QPushButton(self.page_Login)
        self.pushButton_L_Sure.setMinimumSize(QtCore.QSize(90, 25))
        self.pushButton_L_Sure.setStyleSheet("QPushButton{\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"background-color: rgb(170, 255, 255);\n"
"min-height:25px;    /*设置最小高度*/\n"
"border-radius:10px;    /*设置圆角半径 */\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:3px;\n"
"padding-left:3px;\n"
"}")
        self.pushButton_L_Sure.setObjectName("pushButton_L_Sure")
        self.verticalLayout_5.addWidget(self.pushButton_L_Sure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:2px;\n"
"    padding-left:2px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_Login.setMinimumSize(QtCore.QSize(0, 16))
        self.pushButton_Login.setStyleSheet("")
        self.pushButton_Login.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon1)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_Register.setEnabled(True)
        self.pushButton_Register.setStyleSheet("")
        self.pushButton_Register.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/注册.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon2)
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout.addWidget(self.pushButton_Register)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget.addWidget(self.page)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        self.label_7.setStyleSheet("font: 10pt \"Arial Rounded MT Bold\";\n"
"color: rgb(255, 85, 255);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setStyleSheet("font: 10pt \"Arial Rounded MT Bold\";\n"
"color: rgb(255, 85, 255);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.page_5)
        self.label_8.setStyleSheet("font: 10pt \"Arial Rounded MT Bold\";\n"
"color: rgb(255, 85, 255);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_9.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setStyleSheet("font: 10pt \"Arial Rounded MT Bold\";\n"
"color: rgb(255, 85, 255);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_4)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 50, 261, 231))
        self.label_4.setMinimumSize(QtCore.QSize(261, 231))
        self.label_4.setStyleSheet("border-radius:100px;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(LoginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", " Water Area Detection System"))
        self.label_2.setText(_translate("LoginWindow", "Have a nice day :)"))
        self.label_3.setText(_translate("LoginWindow", "  By hfuters"))
        self.lineEdit_Register_Account.setPlaceholderText(_translate("LoginWindow", "Account"))
        self.lineEdit_Register_Password.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.pushButton_R_Sure_2.setText(_translate("LoginWindow", "Register"))
        self.lineEdit_Login_Account.setPlaceholderText(_translate("LoginWindow", "Account"))
        self.lineEdit_Login_Password.setPlaceholderText(_translate("LoginWindow", "Password"))
        self.pushButton_L_Sure.setText(_translate("LoginWindow", "Login"))
        self.label_7.setText(_translate("LoginWindow", "The current user already exists!"))
        self.label_6.setText(_translate("LoginWindow", "The account or password is incorrect!"))
        self.label_8.setText(_translate("LoginWindow", "Registered successfully!"))
        self.label_5.setText(_translate("LoginWindow", "The account or password cannot be empty!"))
import res_rc
